services:
  stablediff-rocm:
    build:
      context: .
      dockerfile: Dockerfile.rocm
    container_name: stablediff-rocm-runner
    environment:
      COMMANDLINE_ARGS: >-
        --listen
        --precision full
        --no-half
        --no-half-vae
        --opt-split-attention
        --use-hip
      ROCR_VISIBLE_DEVICES: "0"
      HIP_LAUNCH_BLOCKING: "1"
      HSA_OVERRIDE_GFX_VERSION: "10.3.0"
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    ports:
      - "7860:7860"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
      - render
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./cache:/root/.cache
      - ./stablediff.env:/stablediff.env
      - ./stablediff-web:/stablediff-web
      - ./stablediff-models:/stablediff-web/models/Stable-diffusion
      - ./entrypoint.sh:/entrypoint.sh
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 24G