version: '3'
services:
  stablediff-rocm:
    build: 
      context: .
      dockerfile: Dockerfile.rocm
    container_name: stablediff-rocm-runner
    environment:
      TZ: "Europe/Rome"
      ROC_ENABLE_PRE_VEGA: 1
      COMMANDLINE_ARGS: "--listen --lowvram --no-half --skip-torch-cuda-test"
      HSA_OVERRIDE_GFX_VERSION: "10.3.0"
      ROCR_VISIBLE_DEVICES: 1
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "rocm-smi;
      echo 'Environment:';
      env;
      echo 'Contents of /stablediff-web:';
      ls -la /stablediff-web;
      echo 'Launching Stable Diffusion WebUI:';
      python launch.py $$COMMANDLINE_ARGS"
    ports:
      - "7860:7860"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./models:/stablediff-web/models
    tty: true
    stdin_open: true